(define (problem blocks-problem)
    (:domain blocks)
    (:objects a b c)
    (:init  (on-table a)
            (on-table b)
            (on-table c)
            (clear a)
            (clear b)
            (clear c)
            (handempty)
    )
    (:goal (and (on b c)
                (on a b))
    )
)